### ISSUE TITLE
No link to creat new post 

### ISSUE THREAD

**Issue by vajrabisj** [l1mey112/me.l-m.dev#4]
After running the server which is started at localhost:8080, there is no link on the home page to create new post. Only a search link. How to resolve? Thx in advance.

**Comment by l1mey112** [comment]
To create a new post and do other thing such as editing, deleting, and creating backups, you must be authenticated.

The URL to authenticate yourself is at `/auth`, it's hidden to normal users, after that the should be able to create posts just fine.

**Comment by vajrabisj** [comment]
Really appreciate your prompt reply! Like your blog site very much :)
