### ISSUE TITLE
Systemd to invoke server

### ISSUE THREAD

**Issue by vajrabisj** [l1mey112/me.l-m.dev#5]
Sorry to bother you again. But how I can launch the server through Linux systemd? Tried many times, always can launch but cannot persistent ie exited. Thx.

**Comment by l1mey112** [comment]
You may be missing environment variables and such, set up the systemd script with logging.

**Comment by l1mey112** [comment]
I've converted my FreeBSD RC script to a systemd one.

```
[Unit]
Description=lifestream
After=network.target

[Service]
Type=simple
User=main
WorkingDirectory=/path/to/lifestream
Environment="SECRET=secret_password"
Environment="PORT=8081"
ExecStart=/path/to/lifestream/lifestream
Restart=always

[Install]
WantedBy=multi-user.target
```

You may want to audit this yourself.

**Comment by vajrabisj** [comment]
Really thanks for the prompt reply! Appreciate it so much
